/// Generated by AssetsRefGenerator on 2022/08/12
class Res {
  static const String icon = "assets/img/icon.png";
  static const String IRANSansMobile = "assets/fonts/IRANSansMobile.ttf";
  static const String IRANSansMobile_Black = "assets/fonts/IRANSansMobile_Black.ttf";
  static const String IRANSansMobile_Bold = "assets/fonts/IRANSansMobile_Bold.ttf";
  static const String IRANSansMobile_Light = "assets/fonts/IRANSansMobile_Light.ttf";
  static const String IRANSansMobile_Medium = "assets/fonts/IRANSansMobile_Medium.ttf";
  static const String IRANSansMobile_UltraLight = "assets/fonts/IRANSansMobile_UltraLight.ttf";
  static const String IRANSansX_Bold = "assets/fonts/IRANSansX-Bold.woff";
  static const String IRANSansX_Regular = "assets/fonts/IRANSansX-Regular.woff";
  static const String load = "assets/img/load.png";
  static const String logo = "assets/img/logo.png";
  static const String menu = "assets/img/menu.png";
  static const String programming = "assets/img/programming.png";
  static const String soal = "assets/img/soal.png";
}
